
services:

  website:
    image: ghcr.io/stephen-steyaert-projects/steyaertsite/steyaert-site:latest
    depends_on:
      - db
    env_file:
      - .env.prod
    environment:
      - VIRTUAL_HOST=movies.steyaert.xyz
      - VIRTUAL_PORT=8000
    restart: always
    init: true
    networks:
      - nginx-proxy
      - steyaertsite_net

  db:
    image: postgres:17
    container_name: steyaertsite_db
    expose:
      - "5432"
    volumes:
      - /srv/postgres_data:/var/lib/postgresql/data
    restart: always
    init: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env.prod
    networks:
      - steyaertsite_net

networks:
  steyaertsite_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.55.1.0/24
          gateway: 172.55.1.1
  nginx-proxy:
    external: true
